apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgresql-backup-s3.fullname" $ }}
  labels:
    app: {{ template "postgresql-backup-s3.name" $ }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
    S3_REGION: {{ default "eu-west-2" .Values.config.s3.region }}
    S3_BUCKET: {{ .Values.config.s3.bucket}}
    S3_PREFIX: {{ .Values.config.s3.prefix}}
    POSTGRES_HOST: {{ .Values.config.postgres.host}}
    POSTGRES_DATABASE: {{ .Values.config.postgres.database}}
    POSTGRES_USER: {{ .Values.config.postgres.user}}
    POSTGRES_EXTRA_OPTS: {{ .Values.config.postgres.extra_opts}}