apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgresql-backup-s3.fullname" $ }}
  labels:
    app: {{ template "postgresql-backup-s3.name" $ }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
    S3_REGION: {{ .Values.config.s3.region}}
    S3_BUCKET: {{ .Values.config.s3.bucket}}
    S3_PREFIX: {{ required "Please provide a prefix" .Values.config.s3.prefix}}
    POSTGRES_HOST: {{ required "Please provide a host port" .Values.config.postgres.host}}
    POSTGRES_DATABASE: {{ .Values.config.postgres.database}}
    POSTGRES_USER: {{ required "Please provide a username" .Values.config.postgres.user}}
    POSTGRES_EXTRA_OPTS: {{ .Values.config.postgres.extraOpts}}
    POSTGRES_SECRET: {{ required "Please provide a postgres secret name" .Values.config.postgres.secret}}
    SECRET: {{ required "Please provide a secret name" .Values.config.s3.secret}}