apiVersion: {{ template "cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ template "postgresql-backup-s3.fullname" . }}
  labels:
    app: {{ template "postgresql-backup-s3.name" . }}
    chart: {{ template "postgresql-backup-s3.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations: 
  {{ toYaml .Values.cronjob.annotations | indent 4 }}
spec:
  schedule: "{{ list (randNumeric 1) "0 */1 * *" | join " " }}"
  {{- with .Values.cronjob.concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ template "postgresql-backup-s3.name" . }}
            release: {{ .Release.Name }}
          annotations: 
{{ toYaml .Values.pod.annotations | indent 12 }}
        spec:
          restartPolicy: Never
{{- if .Values.priorityClassName }}
          priorityClassName: "{{ .Values.priorityClassName }}"
{{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: S3_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ required "Please provide a secret name" .Values.config.s3.secret.name}}
                      key: {{ .Values.config.s3.secret.accessKeyIdKey }}
                - name: S3_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ required "Please provide a secret name" .Values.config.s3.secret.name}}
                      key: {{ .Values.config.s3.secret.secretAccessKey }}
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ required "Please provide a postgres secret name" .Values.config.postgres.secret}}
                      key: {{ .Values.config.postgres.secret.password }}
              envFrom:
                - configMapRef:
                    name: {{ template "postgresql-backup-s3.fullname" $ }}
              resources:
{{ toYaml .Values.resources | indent 16 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 12 }}
    {{- end }}