deployments:
  - name: backend
    replicaCount: 1
    migrate:
      command: ["yarn"]
      args: ["migrate"]
    image:
      repository: stackworx/durf-fms-server
      tag: develop
      pullPolicy: IfNotPresent
    service:
      enabled: true
      type: ClusterIP
      externalPort: 80
      internalPort: 5000
    ingress:
      enabled: true
      hosts:
        - api.durf.dev.stackworx.cloud
      annotations:
        kubernetes.io/ingress.class: traefik
    resources: {}
    nodeSelector: 
      type: apps
  - name: scheduler
    replicaCount: 1
    command: ["node"]
    args: ["--harmony_object_rest_spread", "src/tasks/worker/start.js"]
    image:
      repository: stackworx/durf-fms-admin
      tag: develop
      pullPolicy: IfNotPresent
    service:
      enabled: false
    ingress:
      enabled: false
    resources: {}
    nodeSelector: 
      type: apps
  - name: frontend
    replicaCount: 1
    image:
      repository: stackworx/durf-fms-admin
      tag: develop
      pullPolicy: IfNotPresent
    service:
      enabled: true
      type: ClusterIP
      externalPort: 80
      internalPort: 80
    ingress:
      enabled: true
      hosts:
        - admin.durf.dev.stackworx.cloud
      annotations:
        kubernetes.io/ingress.class: traefik
    resources: {}
    nodeSelector: 
      type: apps
imageCredentials:
  registry: index.docker.io/v1/
  username: buildbotstackworx
  password: <password>

postgresql:
  imageTag: 9.6.2
  postgresUser: durf
  postgresDatabase: durf
  # TODO remove this and use a secret
  postgresPassword: rX5QCAJpCn4BHCmA
  postgresInitdbArgs: --data-checksums
  persistence: 
    size: 2Gi
  metrics:
    enabled: true
  nodeSelector: 
    type: apps

redis:
  # image: bitnami/redis:VERSION
  # TODO enable password
  usePassword: false
  persistence: 
    size: 1Gi
  metrics:
    enabled: true
  nodeSelector: 
    type: apps