deployments:
  - name: backend
    replicaCount: 1
    image:
      repository: stackworx/durf-fms-server
      tag: develop
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      externalPort: 80
      internalPort: 5000
    ingress:
      enabled: true
      hosts:
        - admin.durf.dev.stackworx.cloud
      annotations:
        kubernetes.io/ingress.class: traefik
    resources: {}
  - name: frontend
    replicaCount: 1
    image:
      repository: stackworx/durf-fms-admin
      tag: develop
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      externalPort: 80
      internalPort: 80
    ingress:
      enabled: true
      hosts:
        - api.durf.dev.stackworx.cloud
      annotations:
        kubernetes.io/ingress.class: traefik
    resources: {}
