{{- if .Values.ingress.basicAuth.enabled }}
{{- $fullName := include "traefikv2-ingress.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-basic-auth
spec:
  basicAuth:
    secret: {{ .Values.ingress.basicAuth.secretName }}
{{- end }}