# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 5

image:
  repository: ''
  tag: develop
  pullPolicy: IfNotPresent
imageCredentials:
  registry: registry.gitlab.com
service:
  enabled: true
  type: ClusterIP
  externalPort: 80
  internalPort: 80
debugService:
  enabled: false
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
resources: {}
probes: {
  enabled: true,
  liveness: {
    path: /health
  },
  readiness: {
    path: /health
  }
}
migration:
  enabled: false
  command: ['yarn']
  args: ['migrate']
env: {}
nodeSelector:
  type: apps

# https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume
# volumeMounts: {}
# volumes: {}