apiVersion: v1
appVersion: "1.0"
description: A Backup cronjob that saves backup in the s3 AWS bucket
name: postgresql-backup-s3
icon: http://stackworx.io/logo-versions/white-512x512.png
version: 0.1.0
