apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" $ }}-env
  labels:
    app: {{ template "app.name" $ }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
{{- if .Values.env }}
{{ toYaml .Values.env | indent 2 }}
{{- end -}}
