{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" $ }}-registrykey
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}