{{- if and .Values.service.enabled .Values.ingress.enabled .Values.ingress.traefikV2.enabled }}
{{- $fullName := include "app.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-compress
spec:
  compress: {}
{{- if .Values.ingress.traefikV2.basicAuth.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-basic-auth
spec:
  basicAuth:
    secret: {{ .Values.ingress.traefikV2.basicAuth.secretName }}
{{- end }}
{{- end }}
---
{{- if and .Values.service.enabled .Values.ingress.enabled .Values.ingress.traefikV2.enabled }}
{{-  if and .Values.ingress.enabled (not .Values.ingress.hosts) }}
  {{ fail "ingress.hosts must have at least one host" }}
{{- end }}
{{- $fullName := include "app.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-https
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  entryPoints:
    - https
  tls:
    certResolver: default
  routes:
  - kind: Rule
    {{- $matchExpressions := list }}
    {{- range .Values.ingress.hosts }}
      {{-  $expr := printf "Host(`%s`)" . -}}
      {{- $matchExpressions = append $matchExpressions $expr }}  
    {{- end }}
    match: {{ join " && " $matchExpressions }}
    middlewares:
      - {{ .Release.Namespace }}-{{ $fullName }}-compress@kubernetescrd
      {{- if .Values.ingress.traefikV2.basicAuth.enabled }}
      - name: {{ .Release.Namespace }}-{{ $fullName }}-basic-auth@kubernetescrd
      {{- end }}
    priority: {{ .Values.ingress.priority }}
    services:
    - kind: Service
      name: {{ template "app.fullname" . }}
      port: {{ .Values.service.externalPort | default "80" }}
{{- end }}
---
{{- if and .Values.service.enabled .Values.ingress.enabled .Values.ingress.traefikV2 }}
{{-  if not .Values.ingress.hosts }}
  {{ fail "ingress.hosts must have at least one host" }}
{{- end }}
{{- $fullName := include "app.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-http
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  entryPoints:
    - http
  routes:
  - kind: Rule
    {{- $matchExpressions := list }}
    {{- range .Values.ingress.hosts }}
      {{-  $expr := printf "Host(`%s`)" . -}}
      {{- $matchExpressions = append $matchExpressions $expr }}  
    {{- end }}
    match: {{ join " && " $matchExpressions }}
    middlewares:
      - name: {{ .Release.Namespace }}-{{ $fullName }}-compress@kubernetescrd
      {{- if .Values.ingress.traefikV2.basicAuth.enabled }}
      - name: {{ .Release.Namespace }}-{{ $fullName }}-basic-auth@kubernetescrd
      {{- end }}
    priority: {{ .Values.ingress.priority }}
    services:
    - kind: Service
      name: {{ template "app.fullname" . }}
      port: {{ .Values.service.externalPort | default "80" }}
{{- end }}